FROM node:20-alpine AS deps

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci --frozen-lockfile


FROM node:20-alpine AS builder

WORKDIR /app

# Copy dependencies from previous stage (faster than reinstalling)
COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build


FROM node:20-alpine AS runner

# Set production environment
ENV NODE_ENV=production

WORKDIR /app

# Security: Create a non-root user
# Running as root is dangerous - if app is compromised, attacker has full control
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy public assets (images, fonts, etc.)
COPY --from=builder /app/public ./public

# Create .next directory with correct permissions
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Copy the standalone output
# This includes server.js + minimal node_modules + your app
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Copy static files (JS, CSS generated by Next.js)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Switch to non-root user
USER nextjs


# Document that container listens on port 3000
EXPOSE 3000

# Listen on all interfaces (not just localhost)
ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

# Start the server
# standalone mode creates
CMD ["node", "server.js"]